-- SQLite
DROP TABLE IF EXISTS USUARIO;

CREATE TABLE IF NOT EXISTS USUARIOS (
    USU_ID              INTEGER PRIMARY KEY AUTOINCREMENT,
    USU_USER            TEXT NOT NULL,
    USU_CLAVE           TEXT NOT NULL,
    USU_NOMBRECOMPLETO  TEXT,
    USU_ROL             TEXT,
    USU_ESTADO          INT DEFAULT 1,

    CONSTRAINT ck_usu_rol CHECK (USU_ROL IN ('MEDICO', 'AGENDADOR', 'ADMIN'))
);

INSERT INTO USUARIOS (USU_USER, USU_CLAVE, USU_NOMBRECOMPLETO, USU_ROL)
VALUES ('dr_garcia', 'password123', 'Ricardo Garcia', 'MEDICO');