-- SQLite
DROP TABLE IF EXISTS USUARIO
CREATE TABLE IF NOT EXISTS USUARIO (
    USU_ID              NUM,
    USU_USER            TEXT,
    USU_CLAVE           TEXT,
    USU_NOMBRECOMPLETO  TEXT,
    USU_ROL             TEXT,
    USU_ESTADO          INT DEFAULT 1,

    CONSTRAINT pk_usu_id PRIMARY KEY (USU_ID) AUTOINCREMENT,
    CONSTRAINT ck_usu_rol CHECK (USU_ROL IN ('MEDICO', 'AGENDADOR', 'ADMIN'))
) 