' =====================================================
' DIAGRAMA DE CONTENEDORES - OPCION 1
' =====================================================
@startuml Container

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

' =====================================================
' USUARIOS DEL SISTEMA
' =====================================================

Person(paciente, "Paciente", "Usuario que solicita y consulta citas médicas y revisa su historial clinico")
Person(admin, "Administrador", "Usuario responsable de gestionar usuarios, auditorias y configuraciones del sistema")
Person(medico, "Medico/Terapista", "Profesional de salud que gestiona citas medicas y registra información clinica")

System_Boundary(s1, "Sistema Piedra Azul") {
    Container(app, "Aplicacion de escritorio", "Java + Swing (JFrame)", "Permite la gestion de usuarios, citas medicas e historiales clinicos. Contiene la interfaz grafica, logica de negocio y acceso a datos.")
    ContainerDb(db, "Base de Datos", "SQLite", "Almacena usuarios, citas medicas, historiales clinicos, registros de auditoria y demas informacion del sistema.")
}
Rel(paciente, app, "Solicita y consulta citas medicas", "Interfaz grafica (JFrame)")

Rel(admin, app, "Administra usuarios y configuraciones", "Interfaz grafica (JFrame)")

Rel(medico, app, "Registra informacion clínica y gestiona citas", "Interfaz grafica (JFrame)")

Rel(app, db, "Lee/Escribe", "JDBC")
@enduml